<?php
session_start();
$_SESSION['err'] = 1;
foreach ($_POST as $key => $value) {
	if (trim($value) == '') {
		$_SESSION['err'] = 0;
	}
	break;
}

if ($_SESSION['err'] == 0) {
	header("Location: checkout.php");
} else {
	unset($_SESSION['err']);
}


$_SESSION['ship'] = array();
foreach ($_POST as $key => $value) {
	if ($key != "submit") {
		$_SESSION['ship'][$key] = $value;
	}
}
require_once "./functions/database_functions.php";
// print out header here
$title = "Purchase";
require "./template/header.php";
// connect database
if (isset($_SESSION['cart']) && (array_count_values($_SESSION['cart']))) {
?>
	<table class="table">
		<tr>
			<th>Item</th>
			<th>Price</th>
			<th>Quantity</th>
			<th>Total</th>
		</tr>
		<?php
		foreach ($_SESSION['cart'] as $isbn => $qty) {
			$conn = db_connect();
			$book = mysqli_fetch_assoc(getBookByIsbn($conn, $isbn));
		?>
			<tr>
				<td><?php echo $book['book_title'] . " by " . $book['book_author']; ?></td>
				<td><?php echo "₹" . $book['book_price']; ?></td>
				<td><?php echo $qty; ?></td>
				<td><?php echo "₹" . $qty * $book['book_price']; ?></td>
			</tr>
		<?php } ?>
		<tr>
			<th>&nbsp;</th>
			<th>&nbsp;</th>
			<th><?php echo $_SESSION['total_items']; ?></th>
			<th><?php echo "₹" . $_SESSION['total_price']; ?></th>
		</tr>
		<tr>
			<td>Shipping</td>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
			<td>20.00</td>
		</tr>
		<tr>
			<th>Total Including Shipping</th>
			<th>&nbsp;</th>
			<th>&nbsp;</th>
			<th><?php echo "₹" . ($_SESSION['total_price'] + 20); ?></th>
		</tr>
	</table>
	<?php

	$apiKey = "rzp_test_ROMLyB374J5hEQ";
	require_once "functions\database_functions.php"
	?>
	<script src="https://code.jquery.com/jquery-3.5.0.js"></script>
	<form method="post" action="process.php" class="form-horizontal">
		<?php if (isset($_SESSION['err']) && $_SESSION['err'] == 1) { ?>

		<?php } ?>

		<script src="https://checkout.razorpay.com/v1/checkout.js" data-key="<?php echo $apiKey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys data-amount="<?php echo $_SESSION['total_price'] * 100 + 2000; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35. data-currency="INR" //You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account data-id="<?php echo 'OID' . rand(10, 100) . 'END'; ?>" //Replace with the order_id generated by you in the backend. data-buttontext="Pay with Razorpay" data-name="RJ BookStore" data-description="Online Book Store" data-image="https://image.freepik.com/free-vector/logo-sample-text_355-558.jpg" data-theme.color="#528FF0"></script>
		<input type="hidden" custom="Hidden Element" name="hidden">
	</form>

<?php
} else {
	echo "<p class=\"text-warning\">Your cart is empty! Please make sure you add some books in it!</p>";
}
if (isset($conn)) {
	mysqli_close($conn);
}
require_once "./template/footer.php";
?>